import Link from 'next/link'
import SiteNav from '../../components/SiteNav'
import SiteFooter from '../../components/SiteFooter'

export const metadata = { title: 'Privacy Policy — Vault' }

export default function Privacy() {
  return (
    <>
      <SiteNav />
      <div className="page-wrap">
        <div className="page-eyebrow">LEGAL</div>
        <h1>Privacy Policy</h1>
        <p className="page-updated">Last updated: July 27, 2026</p>

        <p>Vault Intelligence (&quot;Vault&quot;, &quot;we&quot;) provides AI-generated economic intelligence for Hypixel Skyblock.
        Vault is an independent, unofficial project and is <strong>not affiliated with Hypixel Inc. or Mojang</strong>.
        This page explains what data we collect, why, how long we keep it, and how you can access or remove it.</p>

        <h2>What we collect</h2>
        <ul>
          <li><strong>Account data</strong> — the email address and username you sign up with, and your password (stored hashed by Supabase Auth, never in plain text and never seen by us).</li>
          <li><strong>Billing data</strong> — your subscription plan and Stripe customer/subscription identifiers. Vault never stores your card details; Stripe handles payment information directly.</li>
          <li><strong>Hypixel account link</strong> — the Minecraft/Hypixel username and UUID you choose to link to your Vault account.</li>
          <li><strong>SkyBlock game data</strong> — once you link an account and click &quot;Sync&quot;, we fetch your public SkyBlock profile from Hypixel&rsquo;s official API: skills, slayers, dungeons, collections, pets, fairy souls, and your equipped/stored gear (decoded from item data to price your networth and personalize progression suggestions). This data is only fetched when you explicitly trigger a sync — never on a recurring schedule in the background.</li>
          <li><strong>Technical data</strong> — standard server request logs (IP address, timestamp, requested route) generated automatically by our hosting provider (Vercel) for security and abuse prevention. We do not run third-party advertising trackers or analytics scripts.</li>
        </ul>

        <h2>Where it comes from</h2>
        <p>Directly from you (email, username, password at signup), and from Hypixel&rsquo;s public API for your SkyBlock profile — fetched only for the single Hypixel account you&rsquo;ve linked, only when you ask us to sync.</p>

        <h2>Cookies</h2>
        <p>Vault uses only strictly necessary cookies: an authentication session cookie (Supabase Auth) so you stay
        signed in, and cookies set by Stripe during checkout to process payment securely. We do not use advertising
        cookies, third-party tracking pixels, or analytics cookies that follow you across other sites.</p>

        <h2>Legal basis for processing (EU/UK users)</h2>
        <p>We process account and billing data because it&rsquo;s necessary to perform our contract with you (running
        the service you signed up for). We process your linked SkyBlock game data based on your explicit action
        (choosing to link an account and trigger a sync) — you can unlink or delete it at any time. We rely on
        legitimate interest for basic security logs needed to keep the service reliable and prevent abuse.</p>

        <h2>How we use it</h2>
        <p>To run the product: your dashboard, market intelligence, and — for your own linked Hypixel account — personalized Skills/Milestones analysis generated by Claude (Anthropic&rsquo;s AI). We do not sell your data or share it with third parties beyond the processors necessary to run the service: Supabase (database/authentication), Stripe (billing), Vercel (hosting/infrastructure), and Anthropic (AI analysis calls on your synced game data).</p>

        <h2>International data transfers</h2>
        <p>Our service providers (Supabase, Stripe, Vercel, Anthropic) may process and store data on servers
        located outside your own country, including in the United States. Each of these providers maintains
        their own safeguards for cross-border data transfers under applicable data protection law.</p>

        <h2>Data security</h2>
        <p>We rely on our infrastructure providers&rsquo; security practices (encrypted connections, hashed
        credentials, access-controlled databases) and apply row-level access policies so that account data is
        only reachable by its owner or by the service itself. No system is perfectly secure, and we cannot
        guarantee absolute protection against every possible attack.</p>

        <h2>How long we keep it</h2>
        <p>For as long as your account exists. If you cancel your subscription, your account and data remain until you either delete your account or ask us to remove it.</p>

        <h2>Your rights</h2>
        <p>Depending on where you live, you may have the right to access, correct, export (data portability), or
        object to our processing of your personal data, in addition to the right to delete it outlined below. To
        exercise any of these rights, contact us at <a href="mailto:privacy@vault-intel.app">privacy@vault-intel.app</a> —
        we&rsquo;ll respond within a reasonable time. If you believe we have not handled your data properly, you
        may also lodge a complaint with your local data protection authority.</p>
        <p>You can permanently delete your account and all associated data at any time from your <Link href="/profile">Profile</Link> page. Deleting your account:</p>
        <ul>
          <li>Immediately cancels any active subscription (no further charges)</li>
          <li>Removes your synced SkyBlock game data, Skills cards, missions and progress</li>
          <li>Removes your Hypixel account link</li>
          <li>Removes your subscription/billing record</li>
          <li>Deletes your Vault account itself</li>
        </ul>
        <p>This action is <strong>irreversible</strong>. If you&rsquo;d rather we handle a deletion request manually, or have any other question about your data, contact us at <a href="mailto:privacy@vault-intel.app">privacy@vault-intel.app</a>.</p>

        <h2>Children&rsquo;s privacy</h2>
        <p>Vault is not directed at children and is not intended for use by anyone under the age of 13. We do not
        knowingly collect personal data from children under 13. If you believe a child has provided us with
        personal data, contact us and we will remove it.</p>

        <h2>Changes</h2>
        <p>We may update this policy as the product evolves. Material changes will be reflected here with an updated date.</p>

        <Link href="/" className="page-back">← Back to Vault</Link>
      </div>
      <SiteFooter />
    </>
  )
}
