import Link from 'next/link'
import SiteNav from '../../components/SiteNav'
import SiteFooter from '../../components/SiteFooter'

export const metadata = { title: 'Privacy Policy — Vault' }

export default function Privacy() {
  return (
    <>
      <SiteNav />
      <div className="page-wrap">
        <div className="page-eyebrow">LEGAL</div>
        <h1>Privacy Policy</h1>
        <p className="page-updated">Last updated: July 23, 2026</p>

        <p>Vault Intelligence (&quot;Vault&quot;, &quot;we&quot;) provides AI-generated economic intelligence for Hypixel Skyblock.
        Vault is an independent, unofficial project and is <strong>not affiliated with Hypixel Inc. or Mojang</strong>.
        This page explains what data we collect, why, and how you can remove it.</p>

        <h2>What we collect</h2>
        <ul>
          <li><strong>Account data</strong> — the email address and username you sign up with, and your password (stored hashed by Supabase Auth, never in plain text and never seen by us).</li>
          <li><strong>Billing data</strong> — your subscription plan and Stripe customer/subscription identifiers. Vault never stores your card details; Stripe handles payment information directly.</li>
          <li><strong>Hypixel account link</strong> — the Minecraft/Hypixel username and UUID you choose to link to your Vault account.</li>
          <li><strong>SkyBlock game data</strong> — once you link an account and click &quot;Sync&quot;, we fetch your public SkyBlock profile from Hypixel&rsquo;s official API: skills, slayers, dungeons, collections, pets, fairy souls, and your equipped/stored gear (decoded from item data to price your networth and personalize progression suggestions). This data is only fetched when you explicitly trigger a sync — never on a recurring schedule in the background.</li>
        </ul>

        <h2>Where it comes from</h2>
        <p>Directly from you (email, username, password at signup), and from Hypixel&rsquo;s public API for your SkyBlock profile — fetched only for the single Hypixel account you&rsquo;ve linked, only when you ask us to sync.</p>

        <h2>How we use it</h2>
        <p>To run the product: your dashboard, market intelligence, and — for your own linked Hypixel account — personalized Skills/Milestones analysis generated by Claude (Anthropic&rsquo;s AI). We do not sell your data or share it with third parties beyond the processors necessary to run the service: Supabase (database/authentication), Stripe (billing), and Anthropic (AI analysis calls on your synced game data).</p>

        <h2>How long we keep it</h2>
        <p>For as long as your account exists. If you cancel your subscription, your account and data remain until you either delete your account or ask us to remove it.</p>

        <h2>Your rights</h2>
        <p>You can permanently delete your account and all associated data at any time from your <Link href="/profile">Profile</Link> page. Deleting your account:</p>
        <ul>
          <li>Immediately cancels any active subscription (no further charges)</li>
          <li>Removes your synced SkyBlock game data, Skills cards, missions and progress</li>
          <li>Removes your Hypixel account link</li>
          <li>Removes your subscription/billing record</li>
          <li>Deletes your Vault account itself</li>
        </ul>
        <p>This action is <strong>irreversible</strong>. If you&rsquo;d rather we handle a deletion request manually, or have any other question about your data, contact us at <a href="mailto:privacy@vault-intel.app">privacy@vault-intel.app</a>.</p>

        <h2>Changes</h2>
        <p>We may update this policy as the product evolves. Material changes will be reflected here with an updated date.</p>

        <Link href="/" className="page-back">← Back to Vault</Link>
      </div>
      <SiteFooter />
    </>
  )
}
