import Link from 'next/link'

export const metadata = { title: 'Privacy Policy — Vault' }

export default function Privacy() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #0a0a0a; color: #e8e6df; font-family: 'Space Grotesk', sans-serif; }
        .wrap { max-width: 720px; margin: 0 auto; padding: 3rem 1.5rem 5rem; }
        .logo { font-family: 'Space Mono', monospace; font-size: 1rem; font-weight: 700; color: #c9a84c; letter-spacing: 0.12em; text-decoration: none; }
        .updated { font-size: 0.8rem; color: #6b6960; margin: 0.5rem 0 2.5rem; }
        h1 { font-size: 1.6rem; margin: 2rem 0 0.5rem; }
        h2 { font-size: 1.05rem; color: #c9a84c; margin: 2rem 0 0.6rem; }
        p, li { font-size: 0.9rem; line-height: 1.65; color: #cfcdc4; }
        ul { margin: 0.5rem 0 0.5rem 1.2rem; }
        a { color: #c9a84c; }
        .back { display: inline-block; margin-top: 3rem; font-size: 0.85rem; color: #6b6960; text-decoration: none; }
      `}</style>
      <div className="wrap">
        <Link href="/" className="logo">VAULT.</Link>
        <h1>Privacy Policy</h1>
        <p className="updated">Last updated: July 23, 2026</p>

        <p>Vault Intelligence ("Vault", "we") provides AI-generated economic intelligence for Hypixel Skyblock.
        Vault is an independent, unofficial project and is <strong>not affiliated with Hypixel Inc. or Mojang</strong>.
        This page explains what data we collect, why, and how you can remove it.</p>

        <h2>What we collect</h2>
        <ul>
          <li><strong>Account data</strong> — the email address and username you sign up with, and your password (stored hashed by Supabase Auth, never in plain text and never seen by us).</li>
          <li><strong>Billing data</strong> — your subscription plan and Stripe customer/subscription identifiers. Vault never stores your card details; Stripe handles payment information directly.</li>
          <li><strong>Hypixel account link</strong> — the Minecraft/Hypixel username and UUID you choose to link to your Vault account.</li>
          <li><strong>SkyBlock game data</strong> — once you link an account and click "Sync", we fetch your public SkyBlock profile from Hypixel's official API: skills, slayers, dungeons, collections, pets, fairy souls, and your equipped/stored gear (decoded from item data to price your networth and personalize progression suggestions). This data is only fetched when you explicitly trigger a sync — never on a recurring schedule in the background.</li>
        </ul>

        <h2>Where it comes from</h2>
        <p>Directly from you (email, username, password at signup), and from Hypixel's public API for your SkyBlock profile — fetched only for the single Hypixel account you've linked, only when you ask us to sync.</p>

        <h2>How we use it</h2>
        <p>To run the product: your dashboard, market intelligence, and — for your own linked Hypixel account — personalized Skills/Milestones analysis generated by Claude (Anthropic's AI). We do not sell your data or share it with third parties beyond the processors necessary to run the service: Supabase (database/authentication), Stripe (billing), and Anthropic (AI analysis calls on your synced game data).</p>

        <h2>How long we keep it</h2>
        <p>For as long as your account exists. If you cancel your subscription, your account and data remain until you either delete your account or ask us to remove it.</p>

        <h2>Your rights</h2>
        <p>You can permanently delete your account and all associated data at any time from your <Link href="/profile">Profile</Link> page. Deleting your account:</p>
        <ul>
          <li>Immediately cancels any active subscription (no further charges)</li>
          <li>Removes your synced SkyBlock game data, Skills cards, missions and progress</li>
          <li>Removes your Hypixel account link</li>
          <li>Removes your subscription/billing record</li>
          <li>Deletes your Vault account itself</li>
        </ul>
        <p>This action is <strong>irreversible</strong>. If you'd rather we handle a deletion request manually, or have any other question about your data, contact us at <a href="mailto:privacy@vault-intel.app">privacy@vault-intel.app</a>.</p>

        <h2>Changes</h2>
        <p>We may update this policy as the product evolves. Material changes will be reflected here with an updated date.</p>

        <Link href="/" className="back">← Back to Vault</Link>
      </div>
    </>
  )
}
